import {
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Award,
  Bell,
  Building2,
  Cake,
  ChartLine,
  Check,
  ChevronDown,
  ChevronRight,
  ClipboardCheck,
  Clock,
  CircleHelp,
  Download,
  EllipsisVertical,
  File,
  FileText,
  FileX,
  Filter,
  Folder,
  Gift,
  Heart,
  LayoutGrid,
  LogOut,
  Mail,
  Moon,
  PhilippinePeso,
  Phone,
  Plane,
  Plus,
  RefreshCw,
  Search,
  Send,
  Settings,
  Shield,
  SquareCheckBig,
  SquarePen,
  Star,
  Sun,
  TrendingUp,
  TriangleAlert,
  Upload,
  User,
  Users,
  Wallet,
  type LucideIcon,
} from "lucide-react";

/**
 * Maps the prototype's icon names (drafts/src/icons.jsx) to lucide-react.
 * Lets data reference icons by string (e.g. `icon: "refresh"`).
 */
export const I = {
  grid: LayoutGrid,
  users: Users,
  fileText: FileText,
  shield: Shield,
  refresh: RefreshCw,
  clipboard: ClipboardCheck,
  plane: Plane,
  folder: Folder,
  check: Check,
  checkSquare: SquareCheckBig,
  heart: Heart,
  chart: ChartLine,
  settings: Settings,
  search: Search,
  bell: Bell,
  chevDown: ChevronDown,
  chevRight: ChevronRight,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  trendUp: TrendingUp,
  sun: Sun,
  moon: Moon,
  wallet: Wallet,
  peso: PhilippinePeso,
  alertTri: TriangleAlert,
  fileMissing: FileX,
  clock: Clock,
  cake: Cake,
  award: Award,
  gift: Gift,
  filter: Filter,
  plus: Plus,
  download: Download,
  more: EllipsisVertical,
  phone: Phone,
  mail: Mail,
  doc2: File,
  upload: Upload,
  logout: LogOut,
  user: User,
  help: CircleHelp,
  building: Building2,
  send: Send,
  star: Star,
  edit: SquarePen,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof I;
