"use client";
import Link from "next/link";
import type { Currency, MoneyTotals, ReportFamily, ReportPeriod, ReportsData } from "@/lib/queries/reports";
import { cn } from "@/lib/utils";
import { I } from "../icons";
import { Card, CardHead, PageHead } from "../primitives";

const FAMILY_LABELS:Record<ReportFamily,string>={overview:"Overview",sales:"Sales",commission:"Commission",agents:"Agents",conversion:"Conversion",renewal:"Renewal"};
const PERIOD_LABELS:Record<ReportPeriod,string>={ytd:"YTD",quarter:"Quarter",month:"Month"};
const SYMBOL:Record<Currency,string>={PHP:"₱",USD:"US$",EUR:"€"};
const money=(amount:number,currency:Currency)=>`${SYMBOL[currency]}${amount.toLocaleString("en-PH",{maximumFractionDigits:2})}`;
const moneyLines=(totals:MoneyTotals)=>(["PHP","USD","EUR"] as Currency[]).filter(c=>totals[c]!==0).map(c=>money(totals[c],c));
const query=(data:ReportsData,patch:Partial<{family:ReportFamily;period:ReportPeriod;drill:string|null;format:string}>)=>{const p=new URLSearchParams({family:patch.family??data.filters.family,period:patch.period??data.filters.period});const drill=patch.drill===undefined?data.filters.drill:patch.drill;if(drill)p.set("drill",drill);if(patch.format)p.set("format",patch.format);return p.toString()};
function StatValue({stat}:{stat:ReportsData["stats"][number]}){if(stat.amounts){const lines=moneyLines(stat.amounts);return <>{lines.length?lines.map(v=><div key={v}>{v}</div>):"—"}</>}const percent=stat.label.toLowerCase().includes("rate")||stat.label.toLowerCase().includes("conversion");return <>{percent?`${(stat.value??0).toFixed(1)}%`:(stat.value??0).toLocaleString("en-PH")}</>}

export function ReportsScreen({data}:{data:ReportsData}){return <div>
  <PageHead icon={I.chart} title="Reports" sub={`Performance overview · ${data.periodLabel}`} actions={<><div className="inline-flex rounded-md border border-border-strong bg-card p-0.5">{(Object.keys(PERIOD_LABELS) as ReportPeriod[]).map(period=><Link key={period} href={`/reports?${query(data,{period,drill:null})}`} className={cn("h-7 rounded-[6px] px-3 pt-1 text-[12.5px] font-semibold",period===data.filters.period?"bg-brand-soft text-brand-hover":"text-muted-foreground hover:text-foreground")}>{PERIOD_LABELS[period]}</Link>)}</div><div className="flex items-center gap-1"><I.download size={15}/>{(["xlsx","ods","csv"] as const).map(format=><a key={format} href={`/api/reports/export?${query(data,{format})}`} className="rounded-md border border-border-strong bg-card px-2 py-2 text-[11px] font-bold uppercase hover:bg-hover">{format}</a>)}</div></>}/>
  <nav className="mb-4 flex gap-1 overflow-x-auto border-b border-border-soft">{(Object.keys(FAMILY_LABELS) as ReportFamily[]).map(family=><Link key={family} href={`/reports?${query(data,{family,drill:null})}`} className={cn("border-b-2 px-3 py-2 text-[13px] font-semibold",family===data.filters.family?"border-brand text-brand-hover":"border-transparent text-muted-foreground hover:text-foreground")}>{FAMILY_LABELS[family]}</Link>)}</nav>
  {data.sourceCapNotice&&<div role="status" className="mb-4 rounded-md border border-amber-border bg-amber-soft px-4 py-3 text-[12px] font-semibold text-amber">{data.sourceCapNotice}</div>}
  <div className="mb-4 grid grid-cols-4 gap-3 max-[900px]:grid-cols-2">{data.stats.map(stat=>{const href=`/reports?${query(data,{family:stat.family??data.filters.family,drill:stat.drill??null})}`;const body=<div className="rounded-lg border border-border bg-card px-4 py-3.5 shadow-sm transition hover:border-border-strong"><div className="text-[21px] font-[760] leading-tight tracking-[-0.02em] tabular-nums text-brand-hover"><StatValue stat={stat}/></div><div className="mt-1.5 text-[12.5px] font-[550] text-muted-foreground">{stat.label}</div>{stat.comparison&&<div className="mt-1 text-[11px] text-subtle">vs {data.comparisonLabel}: {stat.comparison}</div>}</div>;return <Link key={stat.label} href={href}>{body}</Link>})}</div>
  <div className="mb-4 grid grid-cols-2 gap-4 max-[900px]:grid-cols-1">{data.charts.map(chart=><Card key={chart.title}><CardHead icon={I.trendUp} title={chart.title}/><div className="space-y-2 px-5 py-4">{chart.restricted?<p className="py-8 text-center text-[13px] text-muted-foreground">Restricted for your role. Agency totals remain available above.</p>:chart.points.length===0?<p className="py-8 text-center text-[13px] text-muted-foreground">No activity in this period.</p>:chart.points.map(point=>{const max=Math.max(...chart.points.map(p=>p.count),1);return <Link key={`${chart.title}-${point.label}`} href={`/reports?${query(data,{drill:point.drill})}`} className="group grid grid-cols-[110px_1fr_auto] items-center gap-3 text-[12px]"><span className="truncate font-semibold">{point.label}</span><span className="h-7 overflow-hidden rounded bg-muted"><span className="flex h-full min-w-1 items-center rounded bg-brand-soft-2 transition group-hover:bg-brand-soft" style={{width:`${Math.max(8,(point.count/max)*100)}%`}}/></span><span className="min-w-12 text-right font-bold tabular-nums">{point.count}</span></Link>})}</div></Card>)}</div>
  <Card><CardHead icon={I.fileText} title="Report detail" action={<div className="flex items-center gap-2 text-[11.5px] text-subtle">{data.filters.drill&&<Link href={`/reports?${query(data,{drill:null})}`} className="font-semibold text-brand-hover">Clear filter</Link>}<span>{data.detailCapped?`First 500 of ${data.detailTotal} records (capped)`:`${data.detailTotal} record${data.detailTotal===1?"":"s"}`}</span></div>}/>{data.filters.drill&&<div className="border-b border-border-soft px-5 py-2 text-[11.5px] text-muted-foreground">Filtered by <span className="rounded bg-brand-soft px-2 py-1 font-semibold text-brand-hover">{data.filters.drill.replace(":"," · ")}</span></div>}<div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[12px]"><thead><tr className="border-b border-border-soft text-[10.5px] uppercase tracking-[.05em] text-subtle">{["Reference","Client","Product / record","Agent","Date","Status","Amount","Note"].map(h=><th key={h} className="px-4 py-2.5">{h}</th>)}</tr></thead><tbody>{data.detail.map(row=><tr key={`${row.href}-${row.id}`} className="border-b border-border-soft last:border-0 hover:bg-muted/40"><td className="px-4 py-3"><Link href={row.href} className="font-mono font-semibold text-brand-hover">{row.reference}</Link></td><td className="px-4 py-3 font-semibold">{row.client}</td><td className="px-4 py-3">{row.product}</td><td className="px-4 py-3 text-muted-foreground">{row.agent}</td><td className="px-4 py-3 text-muted-foreground">{row.date?new Date(row.date).toLocaleDateString("en-PH",{year:"numeric",month:"short",day:"numeric"}):"—"}</td><td className="px-4 py-3">{row.status}</td><td className="px-4 py-3 text-right font-mono font-semibold">{row.amount!=null&&row.currency?money(row.amount,row.currency):row.note?.includes("hidden")?"Restricted":"—"}</td><td className="max-w-48 truncate px-4 py-3 text-muted-foreground">{row.note??"—"}</td></tr>)}{data.detail.length===0&&<tr><td colSpan={8} className="px-4 py-12 text-center text-muted-foreground">No records match this period and filter.</td></tr>}</tbody></table></div></Card>
  <p className="mt-3 text-[11px] text-subtle">Revenue uses verified payments by payment date. Product mix uses issued-record counts. Currency totals are never converted or combined.</p>
</div>}
